name: Build MuPDF.js

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Emscripten
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

          # Install Emscripten
          git clone https://github.com/emscripten-core/emsdk.git /opt/emsdk
          cd /opt/emsdk
          ./emsdk install 3.1.55
          ./emsdk activate 3.1.55
          source ./emsdk_env.sh

      - name: Install Node.js dependencies
        run: npm install

      - name: Check directory structure
        run: |
          echo "Checking directory structure..."
          ls ${{ github.workspace }}
          ls -R libmupdf

      - name: Build MuPDF core
        run: |
          cd ${{ github.workspace }}/libmupdf
          make build=release OS=wasm || true
          ls -R build/wasm/release

      - name: Build project
        run: npm run prepare

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

      - name: Set up git config
        run: |
          git config --global user.email "GitHub Action <action@github.com>"
          git config --global user.name "GitHub Action <action@github.com>"

      - name: Run git add
        run: |
          git add .
          git diff --staged --quiet || echo "CHANGES_DETECTED=true" >> $GITHUB_ENV

      - name: Create Pull Request
        id: cpr
        if: env.CHANGES_DETECTED == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update 3rd Party Licenses"
          committer: GitHub Action <action@github.com>
          author: GitHub Action <action@github.com>
          signoff: true
          branch: update-3rd-party-licenses
          title: "Update 3rd Party Licenses"
          body: |
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: licenses
          draft: false
          delete-branch: true
